### ISSUE TITLE
how to manipulate isaac3d and mpi3d images

### ISSUE THREAD

**Issue by bdseal** [KhrulkovV/nonlinear-image-editing#1]
Thanks for the nice work!

The notebook is easy to edit images for ffhq, cub, and scenes but does not support isaac3d and mpi3d (no pretrained models provided either). Could you provide the usage for isaac3d and mpi3d?

**Comment by KhrulkovV** [comment]
Hey! You mean there are issues with loading pretrained GAN checkpoints or there are no pretrained ODEs for MPI3d and Isaac3D? For the latter I think the pretrained ODEs are lost sadly, but I can try to find them on our old server.
